ALIASES = {
    "bf": "brainfuck",
    "rb": "ruby",
    "rs": "rust",
    "py": "python3",
    "python": "python3",
    "java": "java-jdk",
    "c": "c-gcc",
    "cpp": "cpp-gcc",
    "c++": "cpp-gcc",
    "cs": "cs-core",
    "csharp": "cs-core",
    "js": "javascript-node",
    "javascript": "javascript-node",
    "hs": "haskell",
    "pl": "perl5",
    "perl": "perl5",
    "vb": "vb-core",
    "x86asm": "assembly-fasm",
    "k": "k-ngn",
    "apl": "apl-dyalog",
    "cr": "crystal",
    "clj": "clojure",
}
